echo 'name: VM Creation Workflow

on:
  repository_dispatch:
    types: [payment_success]

jobs:
  create_vm:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify Environment Variables
        run: |
          echo "ARM_CLIENT_ID: $env:ARM_CLIENT_ID"
          echo "ARM_CLIENT_SECRET: $env:ARM_CLIENT_SECRET"
          echo "ARM_SUBSCRIPTION_ID: $env:ARM_SUBSCRIPTION_ID"
          echo "ARM_TENANT_ID: $env:ARM_TENANT_ID"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Install Terraform
        run: |
          $ErrorActionPreference = 'Stop'
          Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_windows_amd64.zip -OutFile terraform.zip
          Expand-Archive -Path terraform.zip -DestinationPath $env:TEMP\terraform
          Copy-Item -Path $env:TEMP\terraform\terraform.exe -DestinationPath C:\Windows\System32\
        shell: pwsh

      - name: Terraform Init
        run: terraform init
        shell: pwsh

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        shell: pwsh' >> .github/workflows/main.yml

